name = "JuliaConPackage"
uuid = "fc2886c6-26cd-4ad3-88c1-c406f8b81920"
authors = ["Walter Lowdermilk <walterlowdermilk@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
